### ISSUE TITLE
Missing Promise require

### ISSUE THREAD

**Issue by dignifiedquire** [petkaantonov/apply-pr#2]
When running the latest version from npm I get this error

```
/Users/dignifiedquire/.nvm/v0.10.38/lib/node_modules/apply-pr/src/validateRef.js:4
    if (ref == null) return Promise.resolve(null);
                            ^
ReferenceError: Promise is not defined
    at Object.exports.branch (/Users/dignifiedquire/.nvm/v0.10.38/lib/node_modules/apply-pr/src/validateRef.js:4:29)
    at Object.<anonymous> (/Users/dignifiedquire/.nvm/v0.10.38/lib/node_modules/apply-pr/src/init.js:48:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dignifiedquire/.nvm/v0.10.38/lib/node_modules/apply-pr/bin/apply-pr:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

Adding 

``` js
var Promise = require('bluebird');
```

to `src/validateRef.js` it starts to work.

**Comment by razh** [comment]
Promises are available natively only in iojs and node 0.12 and up.
